Sidebar Component
projetoKhali/api5front pull request #58
Opened 2024-10-27 13:57 UTC by Incivius

Create the sideBar menu to router at application, in the sidebart i include: Button close, Image Logo at pro4tech and button to go at route.

 
![image](https://github.com/user-attachments/assets/e5d38444-b8dc-483f-8bb6-dece33ea852a)

2024-10-28 03:46 UTC, paulo-granthon requested changes

2024-10-28 03:46 UTC, paulo-granthon commented on src/components/Sidebar.tsx
> +      </View>
trocar o `X` por um ícone

2024-10-28 23:39 UTC, paulo-granthon approved these changes

2024-11-03 15:09 UTC, JhonatanLop approved these changes

2024-11-03 15:13 UTC, merged