Function created for report extraction
projetoKhali/api5front pull request #62
Opened 2024-11-04 22:56 UTC by Incivius

Implementei a função para a extração de relatórios, permitindo ao usuário a extração de um arquivo csv com os dados devidamente filtrados ou não.

[dashboard_data (11).csv](https://github.com/user-attachments/files/17624736/dashboard_data.11.csv)

Exemplo de relatório que o sistema retorna

- resolve #60

2024-11-05 00:21 UTC, paulo-granthon commented on src/pages/Report.tsx
esse arquivo aqui tem muita coisa duplicada da page `Dashboard`, o ideal seria abstrair isso pra um componente em comum talvez, e chamar esse componente nas duas páginas pra evitar repetição de código

2024-11-05 00:25 UTC, paulo-granthon requested changes

2024-11-05 00:25 UTC, paulo-granthon commented on src/service/TableDashboard.ts
> +          'Total de feedbacks': item.numFeedback,
esse mapeamento tá duplicado, o ideal seria fazer uma função que transforma um `DashboardTableRow` em um `FormatedDashboardTableRow` e chamar essa função nos dois lugares

2024-11-06 01:32 UTC, paulo-granthon approved these changes

2024-11-08 00:46 UTC, markusgomes approved these changes

2024-11-08 22:02 UTC, merged